build:
  main: main.go
  binary: gpx
  ldflags: -s -w -X main.version={{.Version}}
  goos:
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
archive:
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  format: tar.gz
  files:
    - license
    - readme.md
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
release:
  github:
    owner: frozzare
    name: gpx